FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY . .
RUN go build -o /app/service ./cmd/service

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/service .
COPY configs/config.yaml ./configs/
EXPOSE 8080
CMD ["./service"]
