.PHONY: run build tidy migrate-up migrate-down migrate-status

CONFIG ?= configs/config.yaml
MIGRATIONS ?= migrations

run:
	go run ./cmd/service -f $(CONFIG)

build:
	go build -o bin/service ./cmd/service

tidy:
	go mod tidy

migrate-up:
	goeasy-cli migrate up --dir . -f $(CONFIG) --migrations $(MIGRATIONS)

migrate-down:
	goeasy-cli migrate down --dir . -f $(CONFIG) --migrations $(MIGRATIONS)

migrate-status:
	goeasy-cli migrate status --dir . -f $(CONFIG) --migrations $(MIGRATIONS)
