package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/txbao/goeasy-cli/internal/schema"
)

func writeCRUDCurlFiles(projectDir string, clients []ClientSurface, meta ModuleMeta, ct schema.ClassifiedTable, force bool) error {
	for _, cl := range clients {
		dir := filepath.Join(APIExamplesDir, cl.Name, meta.Domain, meta.ModuleID)
		rel := filepath.ToSlash(filepath.Join(dir, "crud.http"))
		content := genCRUDHttpFile(cl, meta, ct)
		skipped, err := writeProjectFileOrSkip(projectDir, rel, content, force)
		if err != nil {
			return err
		}
		if skipped {
			fmt.Fprintf(os.Stderr, "info: skip existing %s (use --force)\n", rel)
			continue
		}
		fmt.Printf("  created %s\n", rel)
	}
	return nil
}

func crudBaseURL(cl ClientSurface, meta ModuleMeta) string {
	return fmt.Sprintf("http://127.0.0.1:8080/api/v1/%s%s", cl.Name, meta.RoutePrefix())
}

func genCRUDHttpFile(cl ClientSurface, meta ModuleMeta, ct schema.ClassifiedTable) string {
	base := crudBaseURL(cl, meta)
	var b strings.Builder
	b.WriteString("# Generated by goeasy-cli add db crud\n")
	b.WriteString("@baseUrl = http://127.0.0.1:8080\n")
	if cl.UseAuth {
		b.WriteString("@token = <admin-jwt>\n")
	}
	b.WriteString("\n")
	b.WriteString("### List " + meta.ModuleID + "\n")
	if cl.UseAuth {
		b.WriteString("GET {{baseUrl}}/api/v1/" + cl.Name + meta.RoutePrefix() + "?page=1&page_size=10\n")
		b.WriteString("Authorization: Bearer {{token}}\n\n")
	} else {
		b.WriteString("GET {{baseUrl}}/api/v1/" + cl.Name + meta.RoutePrefix() + "?page=1&page_size=10\n\n")
	}
	b.WriteString("### Get " + meta.ModuleID + " by id\n")
	if cl.UseAuth {
		b.WriteString("GET {{baseUrl}}/api/v1/" + cl.Name + meta.RoutePrefix() + "/1\n")
		b.WriteString("Authorization: Bearer {{token}}\n\n")
	} else {
		b.WriteString("GET {{baseUrl}}/api/v1/" + cl.Name + meta.RoutePrefix() + "/1\n\n")
	}
	if cl.FullCRUD {
		body := curlCreateJSONBody(ct)
		b.WriteString("### Create " + meta.ModuleID + "\n")
		b.WriteString("POST {{baseUrl}}/api/v1/" + cl.Name + meta.RoutePrefix() + "\n")
		b.WriteString("Content-Type: application/json\n")
		if cl.UseAuth {
			b.WriteString("Authorization: Bearer {{token}}\n")
		}
		b.WriteString("\n" + body + "\n\n")
		b.WriteString("### Update " + meta.ModuleID + "\n")
		b.WriteString("PUT {{baseUrl}}/api/v1/" + cl.Name + meta.RoutePrefix() + "/1\n")
		b.WriteString("Content-Type: application/json\n")
		if cl.UseAuth {
			b.WriteString("Authorization: Bearer {{token}}\n")
		}
		b.WriteString("\n{}\n\n")
		b.WriteString("### Delete " + meta.ModuleID + "\n")
		if cl.UseAuth {
			b.WriteString("DELETE {{baseUrl}}/api/v1/" + cl.Name + meta.RoutePrefix() + "/1\n")
			b.WriteString("Authorization: Bearer {{token}}\n")
		} else {
			b.WriteString("DELETE {{baseUrl}}/api/v1/" + cl.Name + meta.RoutePrefix() + "/1\n")
		}
	}
	_ = base
	return b.String()
}

func curlCreateJSONBody(ct schema.ClassifiedTable) string {
	if len(ct.CreateCols) == 0 {
		return "{}"
	}
	parts := make([]string, 0, len(ct.CreateCols))
	for _, c := range ct.CreateCols {
		f := schema.GoFieldFromColumn(c)
		parts = append(parts, fmt.Sprintf("%q:%s", c.Name, curlSampleJSONValue(f.GoType)))
	}
	return "{" + strings.Join(parts, ",") + "}"
}

func curlSampleJSONValue(goType string) string {
	switch {
	case strings.Contains(goType, "int"), goType == "uint", goType == "uint64":
		return "1"
	case goType == "bool":
		return "true"
	case goType == "float64":
		return "1.0"
	default:
		return `"sample"`
	}
}
